package com.example.gon.greenopen.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
/**
 * Entity mapped to table "PERSON".
 */
@Entity
public class Person {

    @Id
    private String name;
    private int age;

    @Generated
    public Person() {
    }

    public Person(String name) {
        this.name = name;
    }

    @Generated
    public Person(String name, int age) {
        this.name = name;
        this.age = age;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getAge() {
        return age;
    }

    public void setAge(int age) {
        this.age = age;
    }

}
